name: Build and deploy
on:
  push:
    branches:
      - 'master'

jobs:
  build-app:
    name: Build application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Check types
        run: npm run check-types
      - name: Run tests
        run: | 
          npm test -- --coverage 
          bash <(curl -s https://codecov.io/bash) -f ./coverage/coverage-final.json

#  publish-app:
#    name: Publish package to npm
#    needs: build-app
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: Install dependencies
#        run: npm ci
#      - name: Publish package
#        run: npm publish --access public
